[cronic] update and squote command line

diff --git a/cronic b/cronic
--- a/cronic
+++ b/cronic
@@ -1,4 +1,4 @@
-#!/bin/sh -ue
+#!/bin/sh -Cue
 #.help
 # % COMMAND..
 #
@@ -10,27 +10,15 @@
 #
 # Based on Cronic v2 by Chuck Houpt <http://habilis.net/cronic/>.
 
-fatal() {
-    printf %s\\n "$(basename "$0") error: $2" >&2
-    exit "$1"
-}
-is_digits() {
-    local x; for x; do case "$x" in *[!0-9]*|'') return 1 ;; *) ;; esac done
-}
-is_integer() {
-    local x; for x; do case "$x" in -*) is_digits "${x#-}" || return 1 ;; *[!0-9]*|'') return 1 ;; *) ;; esac done
-}
+fatal() { rc="$1"; shift; printf %s\\n "${0##*/} error: $*" >&2 || true; exit "$rc"; }
+nonfatal() { printf %s\\n "${0##*/}: $*" >&2 || true; }
+
+is_digits() { for x; do case "$x" in *[!0123456789]*|'') return 1 ;; esac; done; }
 
 max_lines=1000
 sleep_max=0
 handle_option() {
     case "$1" in
-            #[ $# = 2 ] || fatal 64 "missing value for option $1"
-            #[ $# = 1 ] || fatal 64 "unexpected value for option $1"
-            #is_digits "$2" || fatal 64 "expected (non-negative) integer for option $1"
-            #is_integer "$2" || fatal 64 "expected integer for option $1"
-            #[ -n "$2" ] || fatal 64 "empty value for option $1"
-            # $2 is only empty for "--long-option=" (equals with no following value)
         max-lines)
             [ $# = 2 ] || fatal 64 "missing value for option $1"
             is_digits "$2" || fatal 64 "expected (non-negative) integer for option $1"
@@ -42,13 +30,46 @@ handle_option() {
             sleep_max="$(($2 * 60))"
             ;;
         *) fatal 64 "unknown option $1" ;;
-    esac
-}
+        esac
+    }
 while [ $# -gt 0 ]; do
     case "$1" in
         --) shift; break ;;
-        --*=*) x="${1#--}"; handle_option "${x%%=*}" "${x#*=}"; shift ;;
+        --=*) fatal 64 'missing option name' ;;
+        --*=*)
+            x="${1#--}"
+            v="${x#*=}"
+            x="${x%%=*}"
+            case "$x" in
+                :?*|*[\ \`\~\!\@\#\$\%\^\&\*\\\|\;\'\"\?]*) fatal 64 'bad option name' ;;
+                :)
+                    shift
+                    x="$v"
+                    while [ -n "$x" ]; do
+                        v="${x%?}"
+                        set -- -"${x#"$v"}" "$@"
+                        x="$v"
+                        done
+                    ;;
+                *)
+                    handle_option "$x" "$v"
+                    shift
+                    ;;
+                esac
+            ;;
+        --:) shift ;;
+        --:*|--*[\ \`\~\!\@\#\$\%\^\&\*\\\|\;\'\"\?]*) fatal 64 'bad option name' ;;
         --*) handle_option "${1#--}"; shift ;;
+        -[\ \`\~\!\@\#\$\%\^\&\*\=\\\|\;\'\"\?]*) fatal 64 'bad option name' ;;
+        -:*)
+            x="${1#??}"
+            shift
+            while [ -n "$x" ]; do
+                v="${x%?}"
+                set -- -"${x#"$v"}" "$@"
+                x="$v"
+                done
+            ;;
         -?) handle_option "${1#-}"; shift ;;
         -?*)
             v="${1#??}"
@@ -57,50 +78,54 @@ while [ $# -gt 0 ]; do
             shift
             ;;
         *) break ;;
-    esac
-done
-
-if [ $# = 0 ]; then
-    fatal 64 'missing COMMAND arguments'
-fi
+        esac
+    done
+[ $# != 0 ] || fatal 64 'missing COMMAND arguments'
 
 random() {
     # return integer from [0, $1)
     printf %s "$(($(hexdump -e'"%u"' -n4 /dev/urandom) * $1 / 4294967296))"
-}
+    }
 if [ 0 -lt "$sleep_max" ]; then
     sleep "$(random "$sleep_max")"
-fi
+    fi
 
 out="/tmp/cronic.$$.out"
 err="/tmp/cronic.$$.err"
+trap 'rm "$out" "$err"' EXIT
 result=0
 "$@" >"$out" 2>"$err" || result=$?
 
+squote() {
+    while [ $# != 0 ]; do
+        if [ -n "$1" ] && [ x"$(printf %s "$1" | tr -d -c \\055_/0-9A-Za-z)" = x"$1" ]; then
+            printf %s${2+' '} "$1"
+        else
+            printf \'%s\'${2+' '} "$(printf %s "$1" | sed -r s/\'/\'\\\\\'\'/g)"
+            fi
+        shift
+        done
+    }
 if [ $result -ne 0 -o -s "$err" ]; then
     out_lines="$(wc -l <"$out" | sed -r 's/^ +//')"
     err_lines="$(wc -l <"$err" | sed -r 's/^ +//')"
-    cat - <<END
-Cronic detected failure or error output for command:
-$*
-
-Exit status: $result
-
-END
+    printf %s\\n \
+        "Cronic detected failure or error output for command:" \
+        "$(squote "$@")" \
+        "Exit status: $result" \
+        ''
     if [ $err_lines -gt $max_lines ]; then
         printf %s\\n "Error output ($err_lines lines, truncated to $max_lines):"
         head -n"$max_lines" "$err"
     else
         printf %s\\n "Error output ($err_lines lines):"
         cat "$err"
-    fi
+        fi
     if [ $out_lines -gt $max_lines ]; then
         printf \\n%s\\n "Standard output ($out_lines lines, truncated to $max_lines):"
         head -n"$max_lines" "$out"
     else
         printf \\n%s\\n "Standard output ($out_lines lines):"
         cat "$out"
+        fi
     fi
-fi
-
-rm -f "$out" "$err"
