[into] update argument handling

diff --git a/into b/into
--- a/into
+++ b/into
@@ -1,46 +1,16 @@
-#!/bin/sh -ue
+#!/bin/sh -Cue
 # into DEST COMMAND..
 #
 # Rearrange args and execute COMMAND.. DEST.  Useful for tools which append args to generate a command, eg. "find ... -exec into DEST mv".
 
-fatal() {
-    printf '%s: error: %s\n' "$(basename "$0")" "$2" >&2
-    exit "$1"
-}
+fatal() { rc="$1"; shift; printf %s\\n "${0##*/} error: $*" >&2 || true; exit "$rc"; }
 
-handle_option() {
-    fatal 1 "unknown option: $1"
-}
-
-while [ $# -gt 0 ]; do
-    case "$1" in
-        --)
-            shift
-            break;;
-        --*=*)
-            x="${1#--}"
-            handle_option "${x%%=*}" "${x#*=}"
-            shift;;
-        --*)
-            handle_option "${1#--}"
-            shift;;
-        -?*)
-            if [ ${#1} = 2 ]; then
-                handle_option "${1#-}"
-            else
-                v="${1#??}"
-                x="${1%"$v"}"
-                handle_option "${x#-}" "$v"
-            fi
-            shift;;
-        *)
-            break;;
-    esac
-done
-
+while [ $# -gt 0 ]; do case "$1" in --) shift; break ;; -) break ;; -*) fatal 64 'unexpected option' ;; *) break ;; esac; done
 case $# in
-    0|1) fatal 1 'missing arguments';;
-esac
+    0) fatal 64 'missing DEST COMMAND.. arguments' ;;
+    1) fatal 64 'missing COMMAND.. arguments' ;;
+    esac
+
 dest="$1"
 shift
 exec "$@" "$dest"
