[write-to] update, add --clobber; add read-from

diff --git a/write-to b/write-to
--- a/write-to
+++ b/write-to
@@ -1,45 +1,34 @@
-#!/bin/sh -ue
+#!/bin/sh -Cue
 #.help
-# write-to FILE COMMAND..
-# write-to -iX FILE COMMAND..
+# % write-to FILE COMMAND..
 #
 # Run command with standard output redirected to FILE.
 #
 # Options:
 # -a  --append                  append to FILE
 # -iX --in-progress=X           write to FILE.X, rename to FILE on success
-# -IN --in-progress-as=NAME     write to NAME, rename to FILE on success
+# -i  --in-progress             --in-progress=temp
+# -IP --in-progress-as=PATH     write to PATH, rename to FILE on success
 #     --no-keep                 remove in-progress file or FILE on failure
+# -c  --clobber                 overwrite output FILE, if exists
 
 # TODO: maybe rename --no-keep as --discard (--discard-on-error?)
 # TODO: document "opposite" options (--no-append, --no-in-progress, --keep)
 
-fatal() {
-    printf %s\\n "$(basename "$0") error: $2" >&2
-    exit "$1"
-}
-is_digits() {
-    local x; for x; do case "$x" in *[!0-9]*|'') return 1 ;; *) ;; esac done
-}
-is_integer() {
-    local x; for x; do case "$x" in -*) is_digits "${x#-}" || return 1 ;; *[!0-9]*|'') return 1 ;; *) ;; esac done
-}
+fatal() { rc="$1"; shift; printf %s\\n "${0##*/} error: $*" >&2 || true; exit "$rc"; }
+nonfatal() { printf %s\\n "${0##*/}: $*" >&2 || true; }
 
+clobber=false
 append=false
 in_progress=
 in_progress_as=false
 keep=true
 handle_option() {
     case "$1" in
-        # add options here, with common checks:
-            #[ $# = 2 ] || fatal 64 "missing value for option $1"
-            #[ $# = 1 ] || fatal 64 "unexpected value for option $1"
-            #is_digits "$2" || fatal 64 "expected (non-negative) integer for option $1"
-            #is_integer "$2" || fatal 64 "expected integer for option $1"
-        # less commonly useful:
-            #[ -n "$2" ] || fatal 64 "empty value for option $1"
-            # $2 is only empty for "--long-option=" (equals with no following value)
-
+        c|clobber)
+            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
+            clobber=true
+            ;;
         a|append)
             [ $# = 1 ] || fatal 64 "unexpected value for option $1"
             append=true
@@ -49,7 +38,7 @@ handle_option() {
             append=false
             ;;
         i|in-progress)
-            [ $# = 2 ] || fatal 64 "missing value for option $1"
+            [ $# = 2 ] || set -- "$1" temp
             case "$2" in
                 */*) fatal 64 '--in-progress name cannot contain /' ;;
             esac
@@ -77,14 +66,46 @@ handle_option() {
             ;;
 
         *) fatal 64 "unknown option $1" ;;
-    esac
-}
-
+        esac
+    }
 while [ $# -gt 0 ]; do
     case "$1" in
         --) shift; break ;;
-        --*=*) x="${1#--}"; handle_option "${x%%=*}" "${x#*=}"; shift ;;
+        --=*) fatal 64 'missing option name' ;;
+        --*=*)
+            x="${1#--}"
+            v="${x#*=}"
+            x="${x%%=*}"
+            case "$x" in
+                :?*|*[\ \`\~\!\@\#\$\%\^\&\*\\\|\;\'\"\?]*) fatal 64 'bad option name' ;;
+                :)
+                    shift
+                    x="$v"
+                    while [ -n "$x" ]; do
+                        v="${x%?}"
+                        set -- -"${x#"$v"}" "$@"
+                        x="$v"
+                        done
+                    ;;
+                *)
+                    handle_option "$x" "$v"
+                    shift
+                    ;;
+                esac
+            ;;
+        --:) shift ;;
+        --:*|--*[\ \`\~\!\@\#\$\%\^\&\*\\\|\;\'\"\?]*) fatal 64 'bad option name' ;;
         --*) handle_option "${1#--}"; shift ;;
+        -[\ \`\~\!\@\#\$\%\^\&\*\=\\\|\;\'\"\?]*) fatal 64 'bad option name' ;;
+        -:*)
+            x="${1#??}"
+            shift
+            while [ -n "$x" ]; do
+                v="${x%?}"
+                set -- -"${x#"$v"}" "$@"
+                x="$v"
+                done
+            ;;
         -?) handle_option "${1#-}"; shift ;;
         -?*)
             v="${1#??}"
@@ -93,59 +114,65 @@ while [ $# -gt 0 ]; do
             shift
             ;;
         *) break ;;
-    esac
-done
+        esac
+    done
 
 if [ $# = 0 ]; then
     fatal 64 'missing file and command arguments'
 elif [ $# = 1 ]; then
     fatal 64 'missing command argument'
-fi
+    fi
 
-if $append && [ -n "$in_progress" ]; then
-    fatal 64 'cannot append with in-progress file'
-fi
+if $append; then
+    if [ -n "$in_progress" ]; then
+        fatal 64 'cannot --append with --in-progress'
+        fi
+    if $clobber; then
+        fatal 64 'cannot --append and --clobber'
+        fi
+elif $clobber; then
+    set +C
+    fi
 
 output_file="$1"
 shift
 case "$output_file" in
     -*) output_file="./$output_file" ;;
-esac
+    esac
 
 if [ -n "$in_progress" ]; then
     if ! $in_progress_as; then
         in_progress="$output_file.$in_progress"
-    fi
+        fi
     rc=0
-    if $append; then
-        cp "$output_file" "$in_progress"
-        # TODO: what cp options?
-        "$@" 1>>"$in_progress" || rc=$?
-    else
-        "$@" 1>"$in_progress" || rc=$?
-    fi
+    $clobber || [ ! -e "$output_file" ] || fatal 73 "exists: $output_file"
+    $clobber || [ ! -e "$in_progress" ] || fatal 73 "exists: $in_progress"
+    "$@" 1>"$in_progress" || rc=$?
     if [ $rc = 0 ]; then
         mv -f "$in_progress" "$output_file" || fatal 73 "failed to mv -f $in_progress $output_file"
         # TODO: what to do if mv fails?
     elif ! $keep; then
         rm -f "$in_progress" || true
-    fi
+        fi
     exit $rc
 elif ! $keep; then
     rc=0
     if $append; then
-        "$@" 1>>"$output_file" || rc=$?
+        exec 1>>"$output_file"
     else
-        "$@" 1>"$output_file" || rc=$?
-    fi
+        $clobber || [ ! -e "$output_file" ] || fatal 73 "exists: $output_file"
+        exec 1>"$output_file"
+        fi
+    "$@" || rc=$?
     if [ $rc != 0 ]; then
         rm -f "$output_file" || true
-    fi
+        fi
     exit $rc
 else
     if $append; then
         exec "$@" 1>>"$output_file"
     else
+        $clobber || [ ! -e "$output_file" ] || fatal 73 "exists: $output_file"
         exec "$@" 1>"$output_file"
+        fi
     fi
-fi
